### ISSUE TITLE
Interesting idea - maybe similar goals?

### ISSUE THREAD

**Issue by cpaulik** [OGGM/geodown#1]
Hi,

I just wanted to quickly ask what the goals of the project are? Maybe they are compatible with what we are trying to do.
We have implemented packages to download data for geophysical datasets. See e.g. https://github.com/cpaulik/datedown which is used by e.g. https://github.com/TUW-GEO/gldas for downloading the data. 

The datedown package uses wget at the moment but could probably also easily use a pure python solution.

**Comment by fmaussion** [comment]
Thanks for the hint, this was fast! This project is still at a very dirty/draft version: the code exists (and works) in our larger OGGM package, and we have to clean it and make a standalone version of it (I don't know when we will come to this though).

Our goal is to download certain specific datasets we need for the model:
- CRU
- RGI
- DEMs
- Later: CMIP runs
- etc.

I expect the package to be of limited interest to a general audience (with the exception of the DEM part maybe). My wish would be the package to be very small (one module), and I hope we don't have to take too much care about the "download side", but rather about the generation of the correct www paths themselves. 

Using wget for the download is actually not a bad idea! I'll have a look at the package you suggest.

Does that answer your question?

**Comment by cpaulik** [comment]
Yes that answers my question. It was mainly about how general the package should be. 

If you have any suggestions about the datedown package just let me know. At the moment it is only used by us but I tried to write it a little bit general purpose.
